// apps/react-sandbox/src/pages/Home.tsx
import { UiTypography, UiYstack } from "stencil-ui-react-library";

export default function HomePage() {
	return (
		<UiYstack style={{ padding: "20px" }}>
			<UiTypography>React Sandbox</UiTypography>

			<UiTypography variant="p">
				Welcome to the React Sandbox! This is a playground for testing
				and experimenting with various components and features.
			</UiTypography>
		</UiYstack>
	);
}

// apps/angular-sandbox/src/app/pages/home.component.ts
import { CommonModule } from '@angular/common';
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';

@Component({
  selector: 'home-root',
  imports: [CommonModule],
  templateUrl: './home.component.html',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class HomeComponent {}

<ui-ystack style="padding: 20px;">
  <ui-typography>Angular Sandbox</ui-typography>
  <ui-typography variant="p">
    Welcome to the Angular Sandbox! This is a playground for testing
    and experimenting with various components and features.
  </ui-typography>
</ui-ystack>
