// apps/vue-sandbox/src/App.vue
<template>
	<ui-xstack style="align-items: start; gap: 4px">
		<ui-sidebar :items="items" />
		<RouterView />
	</ui-xstack>
</template>

<script>
export default {
  computed: {
    items() {
      return [
        {
          label: "Home",
          icon: "menu",
          active: this.$route.path === "/",
          onClick: () => this.$router.push("/")
        },
        {
          label: "Dashboard",
          icon: "user",
          active: this.$route.path === "/dashboard",
          onClick: () => this.$router.push("/dashboard")
        }
      ]
    }
  }
}
</script>

// apps/angular-sandbox/src/app/app.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import {
  RouterModule,
  RouterOutlet,
  Router,
  NavigationEnd,
} from '@angular/router';
import { Subscription } from 'rxjs';
import { filter } from 'rxjs/operators';

@Component({
  selector: 'app-root',
  imports: [RouterOutlet, RouterModule],
  templateUrl: './app.component.html',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class AppComponent {
  currentRoute: string = '';
  items: any[] = [];
  private routerSubscription!: Subscription;

  constructor(private router: Router) {}

  ngOnInit(): void {
    this.routerSubscription = this.router.events
      .pipe(filter((event) => event instanceof NavigationEnd))
      .subscribe((event: NavigationEnd) => {
        this.currentRoute = event.url;
        this.setItems();
      });

    this.setItems();
  }

  setItems(): void {
    this.items = [
      {
        label: 'Home',
        icon: 'menu',
        active: this.currentRoute === '/',
        onClick: () => this.router.navigate(['/']),
      },
      {
        label: 'Dashboard',
        icon: 'user',
        active: this.currentRoute === '/dashboard',
        onClick: () => this.router.navigate(['/dashboard']),
      },
    ];
  }

  ngOnDestroy(): void {
    if (this.routerSubscription) {
      this.routerSubscription.unsubscribe();
    }
  }
}

<ui-xstack style="align-items: start; gap: 4px;">
  <ui-sidebar [items]="items" />
  <router-outlet></router-outlet>
</ui-xstack>
