// apps/react-sandbox/src/App.tsx
import { UiSidebar, UiXstack } from "stencil-ui-react-library";
import { Route, Routes, useLocation, useNavigate } from "react-router-dom";
import HomePage from "./pages/Home";
import DashboardPage from "./pages/Dashboard";
import "./App.css";

export default function App() {
	const location = useLocation();
	const navigate = useNavigate();

	return (
		<>
			<UiXstack style={{ alignItems: "start" }}>
				<UiSidebar
					items={[
						{
							label: "Home",
							icon: "menu",
							active: location.pathname === "/",
							onClick: () => navigate("/"),
						},
						{
							label: "Dashboard",
							icon: "user",
							active: location.pathname === "/dashboard",
							onClick: () => navigate("/dashboard"),
						},
					]}
				/>

				<Routes>
					<Route path="/" element={<HomePage />} />
					<Route path="/dashboard" element={<DashboardPage />} />
				</Routes>
			</UiXstack>
		</>
	);
}

// apps/vue-sandbox/src/App.vue
<template>
	<ui-xstack style="align-items: start; gap: 4px">
		<ui-sidebar :items="items" />
		<RouterView />
	</ui-xstack>
</template>

<script>
export default {
  computed: {
    items() {
      return [
        {
          label: "Home",
          icon: "menu",
          active: this.$route.path === "/",
          onClick: () => this.$router.push("/")
        },
        {
          label: "Dashboard",
          icon: "user",
          active: this.$route.path === "/dashboard",
          onClick: () => this.$router.push("/dashboard")
        }
      ]
    }
  }
}
</script>
